name: Build dcl-edit
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build-dcl-edit:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Cache Unity files
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}\Library
          key: unity-library
          restore-keys: unity-
          
      - name: Build Windows
        shell: cmd
        run: |
          start "Build" /wait "c:\Program Files\Unity\Hub\Editor\2020.3.21f1\Editor\Unity.exe" \
          -projectPath ${{ github.workspace }} \
          -batchmode \
          -buildWindowsPlayer ${{ github.workspace }}\dcl-edit-version-windows-x86\dcl-edit.exe \
          -quit
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: Some build # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}\Build\testbuild.exe

          
          
